language: python
python:
  - "3.8"
services:
  - mongodb
install:
  - pip install -r requirements.txt
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - python test.py
